export enum Event {
  PLAYER_JOINED = "PLAYER_JOINED",
  ON_PLAYER_JOINED = "ON_PLAYER_JOINED",
  GAME_STARTED = "GAME_STARTED",
  PLAYER_TURN = "PLAYER_TURN",
  ON_PLAYER_MOVED = "ON_PLAYER_MOVED",
  INVALID_MOVE = "INVALID_MOVE",
  PLAYER_WINS = "PLAYER_WINS",
  DRAW = "DRAW",
}
