export enum Event {
  PLAYER_JOINED = "PLAYER_JOINED",
  GAME_STARTED = "GAME_STARTED",
  PLAYER_X_MOVES = "PLAYER_X_MOVES",
  PLAYER_O_MOVES = "PLAYER_O_MOVES",
  PLAYER_X_WINS = "PLAYER_X_WINS",
  PLAYER_O_WINS = "PLAYER_O_WINS",
  DRAW = "DRAW",
}
