name: Docker pipeline for Agones Tic-Tac-Toe BE
on:
  push:
    branches:
      - "main"

jobs:
  Main:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository code
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - id: 'auth'
        uses: google-github-actions/auth@v0
        with:
          credentials_json: '${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}'
      - name: Set up cloud SDK
        uses: google-github-actions/setup-gcloud@v0
      - name: Configure Docker
        run: 'gcloud auth configure-docker asia.gcr.io -q'
      - name: Build and push
        id: build-and-push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/agones-tic-tac-toe-be:latest
      - name: See SHA256 digest
        run: 'echo ${{ steps.build-and-push.outputs.digest }}'
